image: zcorniere/minimal-cpp
stages:
  - compilation
  - test

cache:
  paths:
  - .object/*.o

test:compilation:
  stage: compilation
  script:
    - make re

test:tests_run:
  stage: test
  script:
    - make tests_run
