image: ubuntu:latest

stages:
  - compilation
  - test

cache:
  paths:
  - .object/*.o

before_script:
  - apt-get update && apt-get install software-properties-common -y
  - add-apt-repository ppa:snaipewastaken/ppa
  - apt-get update && apt-get install libncurses-dev clang++ lld -y

test:compilation:
  stage: compilation
  script:
    - make re

test:tests_run:
  stage: test
  script:
    - apt-get install criterion-dev
    - make tests_run
